# Generated by Django 4.1.1 on 2023-04-25 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_carreservation_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('message_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.customuser')),
            ],
        ),
    ]
