# Generated by Django 4.1.1 on 2023-04-25 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_to',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='messageTo', to='product.customuser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageFrom', to='product.customuser'),
        ),
    ]
