# Generated by Django 4.1.1 on 2023-04-25 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_message_message_to_alter_message_message_from'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Messages',
        ),
    ]
