# Generated by Django 4.1.1 on 2023-04-25 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_message_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='message_to',
        ),
    ]
