# Generated by Django 4.1.1 on 2023-04-25 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_messages_message_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.customuser'),
        ),
    ]
