# Generated by Django 4.1.1 on 2023-04-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_messages_message_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_to',
            field=models.IntegerField(default=False),
        ),
    ]
