# Generated by Django 4.1.7 on 2023-04-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_messages_message_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilePic',
            field=models.ImageField(default=False, upload_to='product/static/images'),
        ),
    ]
