# Generated by Django 4.1.7 on 2023-05-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_customuser_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(default=False, upload_to='carImages/'),
        ),
    ]
